meta_product_name: "SecretChef"
meta_title: "Secretchef - Meal Kits with tutorials by professional chefs!"
meta_description: "Selected restaurants in your city are sharing their secrets with you. Simply choose the meals you want to learn and welcome the chef into your kitchen!"
meta_image: "meal_placeholder.jpg" # should exist in `app/assets/images/`
twitter_account: "@secretchef"  # required for Twitter Cards