meta_product_name: "SecretChef"
meta_title: "Secretchef - Meal Kits with professional tutorials by the best chefs in your city!"
meta_description: "Selected restaurants in your city are sharing their secrets with you. Simply choose your restaurant and the meals you want to learn and enjoy a unqiue cooking experience. You receive all ingredients in a kit, together with a professional tutorial by the restaurant's chef!"
meta_image: "meal_placeholder.jpg" # should exist in `app/assets/images/`
twitter_account: "@secretchef"   # required for Twitter Cards